### PR TITLE
Small modification of the equalizer filter

### PR DESCRIPTION
**Pull request by chredeur0**

### CODE REVIEW

**Comment by HazemMeqdad** [comment]
can you give me example how it work?

**Comment by chredeur0** [comment]
It can work like this
image

**Comment by chredeur0** [comment]
Otherwise I have this
```python
    def equalizer(self, bands: List[Dict[int, Union[float]]]):
        """
        There are 15 bands (0-14) that can be changed.

        "gain" is the multiplier for the given band. The default value is 0. Valid values range from -0.25 to 1.0,
        where -0.25 means the given band is completely muted, and 0.25 means it is doubled. Modifying the gain could
        also change the volume of the output.
        """
        update_list = []
        for x in range(0, len(bands)):
            for key, value in bands[x].items():
                if not -1 < key < 15:
                    raise FiltersError("Invalid band, must be 0-14")
                gain = max(min(float(value), 1.0), -0.25)
                band = key
                update_list.append({'band': band, 'gain': gain})
        self._payload["equalizer"] = update_list
```

**Comment by chredeur0** [comment]
Ah and for the other version it works rather like this
image

**Comment by HazemMeqdad** [comment]
> Otherwise I have this
> 
> ```python
>     def equalizer(self, bands: List[Dict[int, Union[float]]]):
>         """
>         There are 15 bands (0-14) that can be changed.
> 
>         "gain" is the multiplier for the given band. The default value is 0. Valid values range from -0.25 to 1.0,
>         where -0.25 means the given band is completely muted, and 0.25 means it is doubled. Modifying the gain could
>         also change the volume of the output.
>         """
>         update_list = []
>         for x in range(0, len(bands)):
>             for key, value in bands[x].items():
>                 if not -1 < key < 15:
>                     raise FiltersError("Invalid band, must be 0-14")
>                 gain = max(min(float(value), 1.0), -0.25)
>                 band = key
>                 update_list.append({'band': band, 'gain': gain})
>         self._payload["equalizer"] = update_list
> ```

i think this not work you need to add key from other if checks like this
```py
if not -1 < key and key < 15:
```

**Comment by HazemMeqdad** [comment]
and commit the new changes

**Comment by chredeur0** [comment]
> > Otherwise I have this
> > ```python
> >     def equalizer(self, bands: List[Dict[int, Union[float]]]):
> >         """
> >         There are 15 bands (0-14) that can be changed.
> > 
> >         "gain" is the multiplier for the given band. The default value is 0. Valid values range from -0.25 to 1.0,
> >         where -0.25 means the given band is completely muted, and 0.25 means it is doubled. Modifying the gain could
> >         also change the volume of the output.
> >         """
> >         update_list = []
> >         for x in range(0, len(bands)):
> >             for key, value in bands[x].items():
> >                 if not -1 < key < 15:
> >                     raise FiltersError("Invalid band, must be 0-14")
> >                 gain = max(min(float(value), 1.0), -0.25)
> >                 band = key
> >                 update_list.append({'band': band, 'gain': gain})
> >         self._payload["equalizer"] = update_list
> > ```
> 
> i think this not work you need to add key from other if checks like this
> 
> ```python
> if not -1 < key and key < 15:
> ```

I tested and everything works if you want me to open another pull request to be able to better see the code?

**Comment by HazemMeqdad** [comment]
no bro just commit the last update and ill approve

**Comment by chredeur0** [comment]
> no bro just commit the last update and ill approve

I committed the update on the fork that I did, I have to do something else?

**Comment by chredeur0** [comment]
I modified another file but I don't think I can add it to the pull request

**Comment by chredeur0** [comment]
Normally it's good

**Comment by HazemMeqdad** [comment]
ty for this updates

**Pull request merged**
